name: Tennis Court Monitor

on:
  workflow_dispatch: # Allow manual triggering
  schedule:
    # Run every 30 minutes from 6 AM to 11 PM UK time (5 AM to 10 PM UTC)
    - cron: '*/30 5-22 * * *'

jobs:
  check-courts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tennis_bot_st_johns/requirements.txt

      - name: Check court availability
        run: python tennis_bot_st_johns/github_runner.py
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
